export const UserRole = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  RECEPTION_STAFF: "RECEPTION_STAFF",
  PHARMACY_STAFF: "PHARMACY_STAFF",
  LAB_STAFF: "LAB_STAFF",
  ADMIN: "ADMIN",
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const VisitStatus = {
  WAITING: "WAITING",
  IN_CONSULTATION: "IN_CONSULTATION",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
